const UnitList = [
    {
        name: 'Anne',
        class: 'Flame Sorcerer',
        lvl: 21,
        model: '/3d/animated.glb',
        thumbnail: '/anne.png',
        artwork: 'link to art work',
        locked: false,
        stats: {
            HP: 35,
            MP: 57,
            STM: 32,
            PATK: 5,
            MATK: 18,
            DEF: 8,
            RES: 12,
            SKILL: 41,
            LUCK: 30,
            AGI: 25,
            MOV: 3,
            JUMP: 2,
        },
        passives: {
            passive1: ['Ember', 'Critical hits deal extra fire damage(30%)'],
            passive2: ['Arcane Knowledge', 'MATK up(20%) when HP and MP are at 100%. Skill BP scales with MP fullness']
        },
        specialSkill: ['BLAZE SALAMANDER', '2-hit fire MATK on enemies in target area that inflicts burn for 3 turns. If enemies are already burned, this attack will crit'],
    },
    {
        name: 'Emi',
        class: 'Decryption Unit',
        lvl: 35,
        model: '/3d/emi.glb',
        thumbnail: '/emi.png',
        artwork: 'link to art work',
        locked: true,
        stats: {
            HP: 43,
            MP: 34,
            STM: 80,
            PATK: 12,
            MATK: 10,
            DEF: 55,
            RES: 15,
            SKILL: 40,
            LUCK: 5,
            AGI: 31,
            MOV: 4,
            JUMP: 1,
        },
        passives: {
            passive1: ['Knowledge Hack', 'Resist MATK damage(40%) for first 5 turns of battle'],
            passive2: ['Automaton', 'DEF towards blunt attacks up(50%). Hit rate +30']
        },
        specialSkill: ['Glance Encryption', 'Non-elemental MATK damage on enemy unit that ignores RES. Inflicts magia nullify for 2 turns on enemy'],
    },
    {
        name: 'Emi',
        class: 'Decryption Unit',
        lvl: 35,
        model: '/3d/emi.glb',
        thumbnail: '/waterpot.png',
        artwork: 'link to art work',
        locked: true,
        stats: {
            HP: 43,
            MP: 34,
            STM: 80,
            PATK: 12,
            MATK: 10,
            DEF: 55,
            RES: 15,
            SKILL: 40,
            LUCK: 5,
            AGI: 31,
            MOV: 4,
            JUMP: 1,
        },
        passives: {
            passive1: ['Knowledge Hack', 'Resist MATK damage(40%) for first 5 turns of battle'],
            passive2: ['Automaton', 'DEF towards blunt attacks up(50%). Hit rate +30']
        },
        specialSkill: ['Glance Encryption', 'Non-elemental MATK damage on enemy unit that ignores RES. Inflicts magia nullify for 2 turns on enemy'],
    },
    {
        name: 'Emi',
        class: 'Decryption Unit',
        lvl: 35,
        model: '/3d/emi.glb',
        thumbnail: '/spedometer.png',
        artwork: 'link to art work',
        locked: true,
        stats: {
            HP: 43,
            MP: 34,
            STM: 80,
            PATK: 12,
            MATK: 10,
            DEF: 55,
            RES: 15,
            SKILL: 40,
            LUCK: 5,
            AGI: 31,
            MOV: 4,
            JUMP: 1,
        },
        passives: {
            passive1: ['Knowledge Hack', 'Resist MATK damage(40%) for first 5 turns of battle'],
            passive2: ['Automaton', 'DEF towards blunt attacks up(50%). Hit rate +30']
        },
        specialSkill: ['Glance Encryption', 'Non-elemental MATK damage on enemy unit that ignores RES. Inflicts magia nullify for 2 turns on enemy'],
    },
    {
        name: 'Emi',
        class: 'Decryption Unit',
        lvl: 35,
        model: '/3d/emi.glb',
        thumbnail: '/chloe.png',
        artwork: 'link to art work',
        locked: true,
        stats: {
            HP: 43,
            MP: 34,
            STM: 80,
            PATK: 12,
            MATK: 10,
            DEF: 55,
            RES: 15,
            SKILL: 40,
            LUCK: 5,
            AGI: 31,
            MOV: 4,
            JUMP: 1,
        },
        passives: {
            passive1: ['Knowledge Hack', 'Resist MATK damage(40%) for first 5 turns of battle'],
            passive2: ['Automaton', 'DEF towards blunt attacks up(50%). Hit rate +30']
        },
        specialSkill: ['Glance Encryption', 'Non-elemental MATK damage on enemy unit that ignores RES. Inflicts magia nullify for 2 turns on enemy'],
    },
];

export default UnitList